name: finalproject
description: A new Flutter project.
publish_to: 'none' # هذا لمنع النشر على pub.dev لأنه مشروع خاص

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  # متوافق مع Flutter SDK 3.5.2

dependencies:
  flutter:
    sdk: flutter

  # خطوط Google Fonts
  google_fonts: ^6.1.0

  # تأثيرات الزجاجية
  glassmorphism: ^3.0.0

  # أيقونات iOS
  cupertino_icons: ^1.0.8

  # حفظ البيانات محلياً
  shared_preferences: ^2.2.2

  # طلبات الشبكة
  http: ^1.2.1

  # خط زمني سهل الاستخدام
  easy_date_timeline: ^2.0.6

  # اختيار الصور من الجهاز
  image_picker: ^0.8.5+3

  # تحميل الصور مع التخزين المؤقت
  cached_network_image: ^3.4.1

  # دعم قاعدة البيانات المحلية SQLite
  sqflite: ^2.3.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # قواعد اللنت لمساعدتك على كتابة كود أنظف
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # لإضافة صور أو أصول (assets)، فعّل الأسطر التالية وأضف مجلد الصور:
  # assets:
  #   - assets/images/

  # لإضافة خطوط مخصصة، استخدم المثال التالي:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
